chat/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    url(r'^', include('core.urls', namespace='core')),

    url(r'^oauth/', include('social_django.urls', namespace='social')),

    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

core/urls.py
from django.conf.urls import url
from django.conf import settings

from .views import log_in, log_out, sign_up, user_list, thread_view, call_view, profile_view, update_profile


urlpatterns = [
    url(r'^login$', log_in, name='login'),
    url(r'^logout$', log_out, name='logout'),
    url(r'^signup$', sign_up, name='signup'),
    url(r'^$', user_list, name='user_list'),
    url(r'^user/(?P<username>.+)$', profile_view, name='user'),
    url(r'^chat/(?P<username>.+)$', thread_view, name='chat'),
    url(r'^thread/(?P<thread_id>.+)$', thread_view, name='thread'),
    url(r'^call/(?P<username>.+)$', call_view, name='call'),
    url(r'^update-profile$', update_profile, name='update_profile'),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static from staticfiles %}
{% load i18n %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta name="robots" content="none">
  <link href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QMOFBUIlPIK7gAAAdxJREFUWMPll8FqFEEQhr/+K6IxqAgBEQ+LoiCKkJMH8RFE8RkEjyJ4M3mBHHwYjSdvQkAQYS+LohcTDWpQoyjioukqDzuDu8asG9nZPqSgT1PM93dVd1cV7HZLozqa7DRwBbgInAVagKrPAbwGOsByEEvu3hmLQpPdNtkHk8UO14bJ5tHomwRAUg2++R/Q7dat6p/DU2DJSCkdDOIRcGbM6X4OnCfxJee8VYCZQdCqHPc2dOZ+AqdIrNYiUh0ad5+V9AbY0/DBz+5+RNLH7Ll3irNnJD2ZALy3X6mdvRcBqyKwAFyd4PU/lFKKiHhYpyBKPELZczKTXQMulxCgpLcqBa/skoC5ggLmksm6Dd77f9mm6ptQyLKAdwUFrAtoFxTQFrBUUMC94g9R3dEsFODPD5Zj2UrVZk3CXmbPJwbKMXAYWJ9ARfwBHCXYyNFXjkl8cvw40G0Q3nX8JKkH39KSKQmZ9oXH9wbgnUS64OFfPfw3s99j2qYJjyaK043s+ZwzCP/rXGCyNeDYGKDvgTvZ8+Iwp6k/4NdHgN+vOuZWXx3ZBFaAp8AycDd7frGjWcBkB4b09d9Mtmiy/ePOzRSAu2OyepT6DLwCngXxmOCBx5jGrO1sRjO7dzr+BVtAwsorwcB8AAAAAElFTkSuQmCC" rel="icon"/>
  <link rel="stylesheet" type="text/css" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}"/>
  {% block css %}{% endblock css %}
  <title>{% block title %}{% trans "Chat room" %}{% endblock title %}</title>
</head>
<body>
<svg class="hidden-xl-down">
  <defs>
    <symbol id="chat-icon" viewBox="0 0 14 14">
      <path d="M7,0.935c-3.866,0-7,2.463-7,5.5c0,1.438,0.703,2.749,1.854,3.729   c-0.044,0.955-0.242,2.239-0.942,2.901c1.337,0,2.706-0.88,3.518-1.514c0.796,0.248,1.663,0.384,2.57,0.384c3.866,0,7-2.463,7-5.5   S10.866,0.935,7,0.935z" fill="#006DF0"/>
    </symbol>
  </defs>
</svg>
  <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse fixed-top">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'core:user_list' %}">Chat</a>

    <div class="collapse navbar-collapse" id="navbar">
      <ul class="navbar-nav mr-auto">
        {% url 'core:user_list' as user_list_url %}
        <li class="nav-item {% if request.get_full_path == user_list_url %}active{% endif %}">
          <a class="nav-link" href="{{ user_list_url }}">Home <span class="sr-only">(current)</span></a>
        </li>
      </ul>
      <ul class="navbar-nav mr-right">
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
        <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <svg class="icon">
            <use xlink:href="#chat-icon" />
          </svg>
           {% if unread_threads %}<span class="badge badge-pill badge-danger">{{ unread_threads }}</span>{% endif %}
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
          {% for thread in threads %}
          <a class="dropdown-item" href="{% url 'core:thread' thread.0 %}">{{ thread.1 }}</a>
          {% endfor %}
        </div>
      </li>
        {% url 'core:user' user.username as user_url %}
        <li class="nav-item {% if request.get_full_path == user_url %}active{% endif %}">
          <a class="nav-link" href="{{ user_url }}">
            <img src="{{ user.profile.avatar.url }}" height="20" width="20" alt="avatar">
            {{ user.username }}
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'core:logout' %}">{% trans "Log out" %}</a>
        </li>
        {% else %}
        {% url 'core:signup' as signup_url %}
        <li class="nav-item {% if request.get_full_path == signup_url %}active{% endif %}">
          <a class="nav-link" href="{{ signup_url }}">{% trans "Sign up" %}</a>
        </li>
        {% url 'core:login' as login_url %}
        <li class="nav-item {% if request.get_full_path == login_url %}active{% endif %}">
          <a class="nav-link" href="{{ login_url }}">{% trans "Log in" %}</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>

  <div class="container">
    {% block content %}{% endblock content %}
  </div>
  <script type="text/javascript" src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'bower_components/tether/dist/js/tether.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'bower_components/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js' %}"></script>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-74402136-5', 'auto');
    ga('send', 'pageview');
  </script>
  {% block script %}{% endblock script %}
</body>
</html>

templates/call.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Video call with" %} {{ interlocutor.username }}{% endblock title %}

{% block content %}
  <div class="jumbotron">

    <div class="container">
        <div class="row">
            <div class="col-xl-8 offset-xl-2 col-lg-10 offset-lg-1 col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h4>{{ interlocutor.username }}</h4>
                    </div>
                    <div id="call-body">
                        <video id="video" muted="muted"></video>
                    </div>
                </div>
                <button id="video-button" class="right" type="button">{% trans "Start video call" %}</button>
            </div>
            </div>
        </div>
    </div>
  </div>
{% endblock content %}

{% block script %}
    <script src="https://rawgit.com/onsip/SIP.js/0.7.5/dist/sip-0.7.5.js"></script>
    <script>
        var domain = 'sipjs.onsip.com';

        var token = 'mkeda';
        var date_now = new Date();
        date_now.setTime(date_now.getTime() + 1000*60*60);
        document.cookie = ('onsipToken=' + token + ';' + 'expires=' + date_now.toUTCString() + ';');

        var fromName = '{{ user.username }}';
        var toName   = '{{ interlocutor.username }}';

        var fromURI  = fromName.toLowerCase() + '.' + token + '@' + domain;
        var toURI    = toName.toLowerCase()   + '.' + token + '@' + domain;

        function createUA(callerURI, displayName) {

            var configuration = {
                traceSip: true,
                uri: callerURI,
                displayName: displayName
            };
            var userAgent = new SIP.UA(configuration);
            return userAgent;
        }

        function mediaOptions(audio, video, remoteRender, localRender) {
            return {
                media: {
                    constraints: {
                        audio: audio,
                        video: video
                    },
                    render: {
                        remote: remoteRender,
                        local: localRender
                    }
                }
            };
        }

        function makeCall(userAgent, target, audio, video, remoteRender, localRender) {
            var options = mediaOptions(audio, video, remoteRender, localRender);
            var session = userAgent.invite('sip:' + target, options);
            return session;
        }

        function setUpVideoInterface(userAgent, target, remoteRenderId, buttonId) {
            var onCall = false;
            var session;
            var remoteRender = document.getElementById(remoteRenderId);
            var button = document.getElementById(buttonId);

            userAgent.on('invite', function (incomingSession) {
                onCall = true;
                session = incomingSession;
                var options = mediaOptions(true, true, remoteRender, null);
                button.firstChild.nodeValue = '{% trans "Hang up" %}';
                session.accept(options);
                session.on('bye', function () {
                    onCall = false;
                    button.firstChild.nodeValue = '{% trans "Start video call" %}';
                    session = null;
                });
            });

            button.addEventListener('click', function () {
                if (onCall) {
                    onCall = false;
                    button.firstChild.nodeValue = '{% trans "Start video call" %}';
                    session.bye();
                    session = null;
                }
                else {
                    onCall = true;
                    button.firstChild.nodeValue = '{% trans "Hang up" %}';
                    session = makeCall(userAgent, target,
                                       true, true,
                                       remoteRender, null);
                    session.on('bye', function () {
                        onCall = false;
                        button.firstChild.nodeValue = '{% trans "Start video call" %}';
                        session = null;
                    });
                }
            });
        }

        (function () {
        if (SIP.WebRTC.isSupported()) {
            window.fromUA = createUA(fromURI, fromName);

            var registrationFailed = false;
            var failRegistration = function () {
                    registrationFailed = true;
                    failInterfaceSetup();
                };

            fromUA.on('registered', setupInterfaces);
            fromUA.on('registrationFailed', failRegistration);
            window.onunload = function () {
                fromUA.stop();
            };

            function setupInterfaces() {
                setUpVideoInterface(fromUA, toURI, 'video', 'video-button');
            }
            function failInterfaceSetup() {
                alert('Max registration limit hit. The app is disabled.');
            }
        }
        })();
    </script>
{% endblock script %}

templates/login.html
{% extends 'base.html' %}
{% load i18n %}
{% load widget_tweaks %}

{% block content %}
  <div class="jumbotron">
  <form action="{% url 'core:login' %}" method="post" class="">
    {% csrf_token %}
    {% if form.non_field_errors %}
    <div class="alert alert-warning col-sm-9 offset-sm-3" role="alert">
      {{ form.non_field_errors }}
    </div>
    {% endif %}
    {% for field in form %}
      <div class="form-group row">
        <label class="col-sm-3 col-form-label">{{ field.label }}</label>
        <div class="col-sm-9">
        {{ field|add_class:"form-control" }}
        {% if field.errors %}
        <div class="alert alert-warning col-sm-9 offset-sm-3" role="alert">
          {{ field.errors }}
        </div>
        {% endif %}
        </div>
      </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary float-right">{% trans "Log in" %}</button>
  </form>


  <a href="{% url 'social:begin' 'facebook' %}">{% trans "Login with Facebook" %}</a>
  <p>{% trans "Don't have an account?" %} <a href="{% url 'core:signup' %}">{% trans "Sign up!" %}</a></p>
  </div>
{% endblock content %}

templates/message.html
<li id="message-{{ message.pk }}" class="{% if user.pk == message.user.pk %}right{% else %}left{% endif %} clearfix message {% if not message %}hidden-xs-up{% endif %}">
    <span class="chat-img">
        <img src="{{ message.avatar }}" width="50" height="50" alt="User Avatar" class="avatar" />
    </span>
    <div class="chat-body clearfix">
        <div class="header">
            <a href="{% if message.user.username %}{% url 'core:user' message.user.username %}{% else %}{% url 'core:user' 'dummy' %}{% endif %}" class="text-muted profile-link">
                <strong class="username primary-font">{{ message.user.username }}</strong>
            </a>
            <small class="text-muted date-wrapper"><time class="date" datetime="{{ message.date }}">{{ message.date|timesince }}</time> ago</small>
        </div>
        <p class="text">{{ message.text }}</p>
    </div>
</li>

templates/profile.html
{% extends 'base.html' %}
{% load i18n %}
{% load widget_tweaks %}

{% block title %}{% trans "Profile" %}{% endblock title %}

{% block content %}
<div class="jumbotron">
<div class="row my-2">
        <div class="col-lg-8 push-lg-4">
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a href="" data-target="#profile" data-toggle="tab" class="nav-link active">{% trans "Profile" %}</a>
                </li>
                <li class="nav-item">
                    {% if is_current_user %}
                    <a href="" data-target="#chats" data-toggle="tab" class="nav-link">{% trans "Chats" %}</a>
                    {% else %}
                    <a href="{% url 'core:chat' profile_user.username %}" class="name nav-link text-muted">{% trans "Chat" %}</a>
                    {% endif %}
                </li>
            </ul>
            <div class="tab-content p-b-3">
                <div class="tab-pane active" id="profile">
                    <h4 class="my-2">User Profile</h4>
                    <div class="row">
                        <div class="col-md-12 mt-3">
                            <div class="form-group row">
                                <div class="col-md-4 float-left"><h6>{% trans "First name" %}</h6></div>
                                <div class="col-md-8 float-right">
                                    {% if is_current_user %}
                                    <a href="#" id="first_name" class="editable" data-type="text" data-pk="first_name" data-url="{% url 'core:update_profile' %}" data-placeholder="{% trans 'Enter first name' %}" data-params="{csrfmiddlewaretoken:'{{csrf_token}}'}">{{ profile_user.first_name }}</a>
                                    {% else %}
                                    {{ profile_user.first_name }}
                                    {% endif %}
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-md-4 float-left"><h6>{% trans "Last name" %}</h6></div>
                                <div class="col-md-8 float-right">
                                    {% if is_current_user %}
                                    <a href="#" id="last_name" class="editable" data-type="text" data-pk="last_name" data-url="{% url 'core:update_profile' %}" data-placeholder="{% trans 'Enter last name' %}" data-params="{csrfmiddlewaretoken:'{{csrf_token}}'}">{{ profile_user.last_name }}</a>
                                    {% else %}
                                    {{ profile_user.last_name }}
                                    {% endif %}
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-md-4 float-left"><h6>{% trans "Email" %}</h6></div>
                                <div class="col-md-8 float-right">
                                    {% if is_current_user %}
                                    <a href="#" id="email" class="editable" data-type="email" data-pk="email" data-url="{% url 'core:update_profile' %}" data-placeholder="{% trans 'Enter email' %}" data-params="{csrfmiddlewaretoken:'{{csrf_token}}'}">{{ profile_user.email }}</a>
                                    {% else %}
                                    {{ profile_user.email }}
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--/row-->
                </div>
                {% if is_current_user %}
                <div class="tab-pane" id="chats">
                    <h4 class="my-2">{% trans "Last chats" %}</h4>
                    <table class="table table-hover table-striped">
                        <tbody>
                             {% for thread in threads %}
                             <tr><td>
                                 <a href="{% url 'core:thread' thread.0 %}" class="name text-muted">{{ thread.1 }}</a>
                             </td></tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="col-lg-4 pull-lg-8 text-center">
            <img src="{{ profile_user.profile.avatar.url }}" class="m-x-auto img-fluid img-circle" alt="avatar">
            {% if is_current_user %}
            <h6 class="mt-2">{% trans "Upload a different photo" %}</h6>
            <form action="{% url 'core:update_profile' %}" method="post" enctype="multipart/form-data" id="avatar-upload">
                {% csrf_token %}
                    {% for field in form %}
                        <label class="custom-file text-left">
                            {{ field|add_class:"custom-file-input" }}
                            <span class="custom-file-control"></span>
                        </label>
                    {% if field.errors %}
                        <div class="alert alert-warning col-sm-9 offset-sm-3" role="alert">
                          {{ field.errors }}
                        </div>
                    {% endif %}
                {% endfor %}
            </form>
            {% endif %}
        </div>
    </div>
  </div>
{% endblock content %}

{% block script %}
  <script>
      // Set up and initialize editable.
      $.fn.editable.defaults.mode = 'inline';
      $('.editable').editable();

      $('#avatar-upload').change(function() {
          console.log('in');
          $(this).submit();
      });
  </script>
{% endblock script %}

templates/signup.html
{% extends 'base.html' %}
{% load i18n %}
{% load widget_tweaks %}

{% block content %}
  <div class="jumbotron">
  <form action="{% url 'core:signup' %}" method="post">
    {% csrf_token %}
    {% if form.non_field_errors %}
    <div class="alert alert-warning col-sm-9 offset-sm-3" role="alert">
      {{ form.non_field_errors }}
    </div>
    {% endif %}
    {% for field in form %}
      <div class="form-group row">
        <label class="col-sm-3 col-form-label">{{ field.label }}</label>
        <div class="col-sm-9">
        {{ field|add_class:"form-control" }}
        </div>
        {% if field.errors %}
        <div class="alert alert-warning col-sm-9 offset-sm-3" role="alert">
          {{ field.errors }}
        </div>
        {% endif %}
      </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary float-right">{% trans "Sign up" %}</button>
    <p>{% trans "Already have an account?" %} <a href="{% url 'core:login' %}">{% trans "Log in!" %}</a></p>
  </form>
  </div>
{% endblock content %}

templates/thread.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Tread" %} {{ thread.name }}{% endblock title %}

{% block content %}
  <div class="jumbotron thread-jumbotron">

    <div class="container">
        <div class="row">
            <div class="col-xl-6 offset-xl-3 col-lg-8 offset-lg-2 col-md-10 offset-md-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h4 class="clearfix">
                            {{ thread.name }}{% if interlocutor %}
                                <a href="{% url 'core:call' interlocutor.username %}" class="h2 float-right">☎</a>
                            {% endif %}
                        </h4>
                    </div>
                    <div id="chat-body" class="panel-body">
                        <ul id="messages" class="chat">
                            {% include "message.html" %}
                            {% for message in messages %}
                                {% include "message.html" %}
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="panel-footer">
                        <div class="input-group">
                            <input id="btn-input" type="text" class="form-control input-sm" placeholder="Type your message here..." />
                            <span class="input-group-btn">
                                <button class="btn btn-warning btn-sm" id="btn-chat">
                                    Send</button>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </div>
{% endblock content %}

{% block script %}
  <script>
    var protocol = location.protocol === 'https:' ? 'wss' : 'ws';
    var socket = new WebSocket(protocol + '://' + window.location.host + '/ws/thread/' + {{ thread.id }});
    var users = {% autoescape off %}{{ users }}{% endautoescape %};
    var user = {{ user.pk }};
    var $input = $('#btn-input');
    var $chat = $('#chat-body');
    var $message;

    function sendMessage() {
      socket.send(JSON.stringify({
        text: $input.val()
      }));
      $input.val('');
    }

    $chat.scrollTop($chat.prop('scrollHeight'));

    $('#btn-chat').click(sendMessage);
    $input.keypress(function(e) {
      if (e.which == 13) {
        sendMessage();
      }
    });

    socket.onopen = function open() {
      console.log('WebSockets connection created.');
    };

    socket.onmessage = function message(event) {
      var raw_data = JSON.parse(event.data);
      var action = raw_data.payload.action;
      var data = raw_data.payload.data;
      var pk = raw_data.payload.pk;

      // On message Update.
      if (action == 'update') {
        $message = $('#message-'+pk);
        $message.find('.text').text(data.text);
      }

      // On message Insert.
      if (action == 'create') {
        $message = $('#message-').clone().toggleClass('left', data.user != user).toggleClass('right', data.user == user).removeClass('hidden-xs-up').attr('id', 'message-' + pk).appendTo('#messages');
        $message.find('.text').text(data.text);
        $message.find('.date').data('date', data.date).text('{% trans "Just now" %}');
        if (users.hasOwnProperty(data.user)) {
          // TODO [Mike] Need to think how to improve this.
          $message.find('.profile-link').attr('href', '/user/' + users[data.user].username);
          $message.find('.username').text(users[data.user].username);
          $message.find('.avatar').attr('src', users[data.user].avatar);
        }

        // Confirm that message was read.
        socket.send(JSON.stringify({
          read: true,
        }));
      }

      // On message Delete.
      if (action == 'delete') {
        $('#message-'+pk).remove();
      }
      $chat.scrollTop($chat.prop('scrollHeight'));
    };

    if (socket.readyState == WebSocket.OPEN) {
      socket.onopen();
    }
  </script>
{% endblock script %}

templates/user_list.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Users" %}{% endblock title %}

{% block content %}
  <div class="jumbotron">

  <ul class="list-group">
    {% for user in users %}
      <li data-username="{{ user.username }}" class="list-group-item justify-content-between">
        <a href="{% url 'core:chat' user.username %}" class="name text-muted">{{ user.username }}</a>
        <span class="status badge badge-default badge-pill {% if user.status %}badge-success{% endif %}">
          {% if user.status %}Online{% else %}Offline{% endif %}
        </span>
      </li>
    {% endfor %}
  </ul>
  </div>
{% endblock content %}

{% block script %}
  <script>
    var protocol = location.protocol === 'https:' ? 'wss' : 'ws';
    var socket = new WebSocket(protocol + '://' + window.location.host + '/ws/users/');

    socket.onopen = function open() {
      console.log('WebSockets connection created.');
    };

    socket.onmessage = function message(event) {
      var data = JSON.parse(event.data);
      // NOTE: We escape JavaScript to prevent XSS attacks.
      var username = encodeURI(data['username']);
      var $user = $('li').filter(function () {
        return $(this).data('username') == username;
      });

      $user.find('.name').text(username);
      if (data['is_logged_in']) {
        $user.find('.status').addClass('badge-success').text('Online');
      }
      else {
        $user.find('.status').removeClass('badge-success').text('Offline');
      }
    };

    if (socket.readyState == WebSocket.OPEN) {
      socket.onopen();
    }
  </script>
{% endblock script %}